apiVersion: v1
kind: Pod
metadata: 
    name: quiz
    labels:
        app: quiz
spec:
    containers:
    - name: quiz
      image: quiz-image:v3
      ports:
      - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: quiz
    labels:
        app: quiz
spec:
    replicas: 1
    selector:
        matchLabels:
            app: quiz
    template:
        metadata:
            labels:
              app: quiz
        spec:
            containers:
            - name: quiz
              image: quiz-image:v3
              ports:
              - containerPort: 80
              
