apiVersion: v1
kind: Pod
metadata: 
    name: rec
    labels:
        app: rec
spec:
    containers:
    - name: rec
      image: rec-image:v2
      imagePullPolicy: Never
      ports:
      - containerPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
    name: rec
    labels:
        app: rec
spec:
    replicas: 1
    selector:
        matchLabels:
            app: rec
    template:
        metadata:
            labels:
              app: rec
        spec:
            containers:
            - name: rec
              image: rec-image:v2
              imagePullPolicy: Never
              ports:
              - containerPort: 80
              
